# (Ignore warnings)

In [17]:
import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')

# Includes

In [45]:
from ucimlrepo import fetch_ucirepo, list_available_datasets
import pandas as pd
from sklearn.datasets import fetch_openml
from tabulate import tabulate

Carreguem dataset, guardem variables a X, variable objectiu a y i dataset complet a heart_disease_df

In [50]:
# import dataset
heart_disease = fetch_ucirepo(id=45)
# alternatively: fetch_ucirepo(name='Heart Disease')

# access data
X = heart_disease.data.features
y = heart_disease.data.targets
# sklearn.linear_model.LinearRegression().fit(X, y)

heart_disease_df = pd.concat([y, X], axis=1)

Mostrem les variables que tenim i informació interessant respecte aquestes.

In [56]:
pd.set_option('display.max_colwidth', None)
display(heart_disease.variables)

,name,role,type,demographic,description,units,missing_values
0,age,Feature,Integer,Age,None,years,no
1,sex,Feature,Categorical,Sex,None,None,no
2,cp,Feature,Categorical,None,None,None,no
3,trestbps,Feature,Integer,None,resting blood pressure (on admission to the hospital),mm Hg,no
4,chol,Feature,Integer,None,serum cholestoral,mg/dl,no
5,fbs,Feature,Categorical,None,fasting blood sugar > 120 mg/dl,None,no
6,restecg,Feature,Categorical,None,None,None,no
7,thalach,Feature,Integer,None,maximum heart rate achieved,None,no
8,exang,Feature,Categorical,None,exercise induced angina,None,no
9,oldpeak,Feature,Integer,None,ST depression induced by exercise relative to rest,None,no
10,slope,Feature,Categorical,None,None,None,no
11,ca,Feature,Integer,None,number of major vessels (0-3) colored by flourosopy,None,yes
12,thal,Feature,Categorical,None,None,None,yes
13,num,Target,Integer,None,diagnosis of heart disease,None,no

Visualitzem la quantitat de NaNs que tenim en la base de dades per columna.

In [55]:
nan_counts = heart_disease_df.isna().sum()
print("Nombre de NaN per columna:")
display(nan_counts)

Nombre de NaN per columna:

num         0
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
dtype: int64

Ara mostrem les files que contenen NaN en algun atribut.

In [57]:
display(heart_disease_df[heart_disease_df.isna().any(axis=1)])

,num,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
87,0,53,0,3,128,216,0,2,115,0,0.0,1,0.0,NaN
166,0,52,1,3,138,223,0,0,169,0,0.0,1,NaN,3.0
192,1,43,1,4,132,247,1,2,143,1,0.1,2,NaN,7.0
266,2,52,1,4,128,204,1,0,156,1,1.0,2,0.0,NaN
287,0,58,1,2,125,220,0,0,144,0,0.4,2,NaN,7.0
302,0,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0